/* FRM205 Jig (Fixture) Library — auto-generated catalog.
   Keyed by A-code reference from FRM205 Testing Instructions V03. */
(function(){
  const P = {
    A1: { code: "J068.1", name: { zh: "前叉假件 (動態)", en: "Fork Dummy (Dynamic)" }, image: "jigs/A1.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D01-01" },
    A2: { code: "J048.1", name: { zh: "Zedler 後輪轂 (剛性用)", en: "Zedler Rear Hub (stiffness)" }, image: "jigs/A2.png", kind: { zh: "輪轂", en: "Hub" }, stock: 2, loc: "H01-01" },
    A3: { code: "J291.1", name: { zh: "Zedler 前輪轂 (剛性用)", en: "Zedler Front Hub (stiffness)" }, image: "jigs/A3.png", kind: { zh: "輪轂", en: "Hub" }, stock: 2, loc: "H01-02" },
    A4: { code: "J267.1", name: { zh: "BB 軸承 (BB 剛性)", en: "BB Bearing (BB stiffness)" }, image: "jigs/A4.png", kind: { zh: "軸承", en: "Bearing" }, stock: 2, loc: "B01-01" },
    A5: { code: "J269.1", name: { zh: "曲柄／鏈條假件", en: "Crank / Chain Dummy" }, image: "jigs/A5.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D01-02" },
    A6: { code: "J311.1 / J554.1", name: { zh: "前軸假件", en: "Front Axle Dummy" }, image: "jigs/A6.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D01-03" },
    A7: { code: "J301.1", name: { zh: "剛性用扭力扳手", en: "Torque Wrench (Stiffness)" }, image: "jigs/A7.png", kind: { zh: "工具", en: "Tool" }, stock: 3, loc: "T01-01" },
    A8: { code: "J016.4", name: { zh: "上 HT 軸承假件", en: "Upper HT Bearing Dummy" }, image: "jigs/A8.png", kind: { zh: "軸承", en: "Bearing" }, stock: 2, loc: "B01-02" },
    A9: { code: "J016.4", name: { zh: "下 HT 軸承假件", en: "Lower HT Bearing Dummy" }, image: "jigs/A9.png", kind: { zh: "軸承", en: "Bearing" }, stock: 2, loc: "B01-03" },
    A10: { code: "J056.1", name: { zh: "後輪轂", en: "Rear Hub" }, image: "jigs/A10.png", kind: { zh: "輪轂", en: "Hub" }, stock: 2, loc: "H01-03" },
    A11: { code: "J190.1", name: { zh: "前輪轂", en: "Front Hub" }, image: "jigs/A11.png", kind: { zh: "輪轂", en: "Hub" }, stock: 2, loc: "H01-04" },
    A17: { code: "J039.6", name: { zh: "BB 軸承 (疲勞用)", en: "BB Bearing Fatigue" }, image: "jigs/A17.png", kind: { zh: "軸承", en: "Bearing" }, stock: 2, loc: "B01-04" },
    A18: { code: "J313.1", name: { zh: "BB 左右墊片 (疲勞用)", en: "BB Spacer L/R (fatigue)" }, image: "jigs/A18.png", kind: { zh: "墊片", en: "Spacer" }, stock: 2, loc: "S01-01" },
    A19: { code: "J070.1 / J071.1 / J072.2", name: { zh: "踏踩疲勞施力治具", en: "Force Introduction — Pedalling Fatigue" }, image: "jigs/A19.png", kind: { zh: "施力治具", en: "Force jig" }, stock: 2, loc: "F01-01" },
    A20: { code: "J277.1", name: { zh: "跳躍負載測試治具", en: "Jump Load Testing Jig" }, image: "jigs/A20.png", kind: { zh: "施力治具", en: "Force jig" }, stock: 2, loc: "F01-02" },
    A21: { code: "J280.1", name: { zh: "座管假件", en: "Seatpost Dummy" }, image: "jigs/A21.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D01-04" },
    A22: { code: "J214.4", name: { zh: "座墊假件", en: "Saddle Dummy" }, image: "jigs/A22.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D02-01" },
    A23: { code: "J275.1", name: { zh: "座墊負載疲勞施力治具", en: "Force Introduction — Seatload Fatigue" }, image: "jigs/A23.png", kind: { zh: "施力治具", en: "Force jig" }, stock: 2, loc: "F01-03" },
    A24: { code: "J219.1", name: { zh: "後碟煞輪轂 (含墊片與軸帽)", en: "Rear Disc Brake Hub" }, image: "jigs/A24.png", kind: { zh: "輪轂", en: "Hub" }, stock: 2, loc: "H02-01" },
    A25: { code: "J217.2", name: { zh: "卡鉗假件", en: "Caliper Dummy" }, image: "jigs/A25.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D02-02" },
    A26: { code: "J151.4", name: { zh: "卡鉗吊架", en: "Caliper Hanger" }, image: "jigs/A26.png", kind: { zh: "固定座", en: "Fixation" }, stock: 2, loc: "X01-01" },
    A27: { code: "J243.2", name: { zh: "碟盤", en: "Disc" }, image: "jigs/A27.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D02-03" },
    A28: { code: "J307.1", name: { zh: "BB 壓入工具", en: "BB Pressing Tool" }, image: "jigs/A28.png", kind: { zh: "工具", en: "Tool" }, stock: 3, loc: "T01-02" },
    A29: { code: "J247.1 +J783.1", name: { zh: "槓桿臂假件 DB (含 32吋延伸)", en: "Lever Arm Dummy DB" }, image: "jigs/A29.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D02-04" },
    A31: { code: "J340.1", name: { zh: "BB 衝擊假件", en: "BB Impact Dummy" }, image: "jigs/A31.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D03-01" },
    A32: { code: "J328.1", name: { zh: "BB 軸承 (衝擊用)", en: "BB Bearing Impact" }, image: "jigs/A32.png", kind: { zh: "軸承", en: "Bearing" }, stock: 2, loc: "B02-01" },
    A33: { code: "J067.2", name: { zh: "衝擊前叉假件", en: "Impact Fork Dummy" }, image: "jigs/A33.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D03-02" },
    A34: { code: "J213.1", name: { zh: "前輪轂衝擊叉 (逆向落架)", en: "Front Hub Impact Fork" }, image: "jigs/A34.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D03-03" },
    A35: { code: "J342.1", name: { zh: "衝擊滾輪", en: "Impact Roll" }, image: "jigs/A35.png", kind: { zh: "治具", en: "Fixture" }, stock: 2, loc: "G01-01" },
    A36: { code: "J365.2 / J365.3", name: { zh: "角度感測器支架", en: "Angle Sensor Holder" }, image: "jigs/A36.png", kind: { zh: "固定座", en: "Fixation" }, stock: 2, loc: "X01-02" },
    A37: { code: "J845.1", name: { zh: "避震器假件 (NEW)", en: "Shock Dummy (NEW)" }, image: "jigs/A37.png", kind: { zh: "假件", en: "Dummy" }, stock: 1, loc: "D03-04" },
    A40: { code: "J384.1", name: { zh: "HT 施力假件", en: "HT Force Introduction Dummy" }, image: "jigs/A40.png", kind: { zh: "施力治具", en: "Force jig" }, stock: 2, loc: "F01-04" },
    A45: { code: "J385.1", name: { zh: "HT 剛性固定錐 (上)", en: "HT Stiffness Fixing Cone Top" }, image: "jigs/A45.png", kind: { zh: "治具", en: "Fixture" }, stock: 2, loc: "G01-02" },
    A46: { code: "J386.1", name: { zh: "HT 剛性固定錐 (下)", en: "HT Stiffness Fixing Cone Bottom" }, image: "jigs/A46.png", kind: { zh: "治具", en: "Fixture" }, stock: 2, loc: "G01-03" },
    A48: { code: "J391.1", name: { zh: "靜態夾持測試假件", en: "Static Clamp Test Dummy" }, image: "jigs/A48.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D04-01" },
    A52: { code: "—", name: { zh: "氣動起子", en: "Impact Screwdriver" }, image: "jigs/A52.png", kind: { zh: "工具", en: "Tool" }, stock: 3, loc: "T01-03" },
    A58: { code: "J537.1", name: { zh: "反持螺帽", en: "Counterhold Nut" }, image: "jigs/A58.png", kind: { zh: "緊固件", en: "Fastener" }, stock: 24, loc: "C01-01" },
    A59: { code: "J345.1 +J847.1/J848.1", name: { zh: "刷負載避震器假件", en: "Shock Dummy — Scrub Load" }, image: "jigs/A59.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D04-02" },
    A62: { code: "J473.1", name: { zh: "刷負載假件前墊片", en: "Spacer Front — Scrubload" }, image: "jigs/A62.png", kind: { zh: "墊片", en: "Spacer" }, stock: 2, loc: "S01-02" },
    A63: { code: "J462.1 +2× J480.1", name: { zh: "可調座管衝擊假件", en: "Adjustable Seatpost Impact Dummy" }, image: "jigs/A63.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D04-03" },
    A73: { code: "J532.1 / J532.2", name: { zh: "可調座管衝擊安裝輔具", en: "Mounting Aid — Seatpost Dummy" }, image: "jigs/A73.png", kind: { zh: "工具", en: "Tool" }, stock: 3, loc: "T01-04" },
    A74: { code: "J540.1", name: { zh: "負載缸延伸", en: "Load Cylinder Extension" }, image: "jigs/A74.png", kind: { zh: "延伸件", en: "Extension" }, stock: 2, loc: "E01-01" },
    A75: { code: "J541.1", name: { zh: "萬向接頭前叉勾爪", en: "Universal Joint Fork Dropout" }, image: "jigs/A75.png", kind: { zh: "固定座", en: "Fixation" }, stock: 2, loc: "X01-03" },
    A76: { code: "J542.1", name: { zh: "後勾爪固定 (鏈支疲勞)", en: "Rear Dropout Fixation — Chain Stay" }, image: "jigs/A76.png", kind: { zh: "固定座", en: "Fixation" }, stock: 2, loc: "X01-04" },
    A77: { code: "J546.1", name: { zh: "前叉勾爪軸承座", en: "Bearing Block — Fork Dropout" }, image: "jigs/A77.png", kind: { zh: "固定座", en: "Fixation" }, stock: 2, loc: "X02-01" },
    A79: { code: "J846.1", name: { zh: "柔性樞軸彎曲治具 (NEW)", en: "Flex Pivot Bending Jigs (NEW)" }, image: "jigs/A79.png", kind: { zh: "治具總成", en: "Fixture assembly" }, stock: 1, loc: "G01-04" },
    A80: { code: "J556.3", name: { zh: "Ultimate 測試前叉假件", en: "Ultimate Test Dummy Fork" }, image: "jigs/A80.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D04-04" },
    A83: { code: "J562.1", name: { zh: "上 HT 軸承假件 Ultimate", en: "Upper HT Bearing Dummy Ultimate" }, image: "jigs/A83.png", kind: { zh: "軸承", en: "Bearing" }, stock: 2, loc: "B02-02" },
    A84: { code: "J562.1", name: { zh: "下 HT 軸承假件 Ultimate", en: "Lower HT Bearing Dummy Ultimate" }, image: "jigs/A84.png", kind: { zh: "軸承", en: "Bearing" }, stock: 2, loc: "B02-03" },
    A85: { code: "—", name: { zh: "萬用負載缸轉接組 M30", en: "Universal Load Cylinder Adaptor M30" }, image: "jigs/A85.png", kind: { zh: "轉接件", en: "Adaptor" }, stock: 2, loc: "R01-01" },
    A86: { code: "J592.1", name: { zh: "前軸向固定 (萬用試驗機)", en: "Frontal Axial Fixation" }, image: "jigs/A86.png", kind: { zh: "固定座", en: "Fixation" }, stock: 2, loc: "X02-02" },
    A87: { code: "J581.2", name: { zh: "後勾爪固定 (萬用試驗機)", en: "Rear DO Fixation (Universal TM)" }, image: "jigs/A87.png", kind: { zh: "固定座", en: "Fixation" }, stock: 2, loc: "X02-03" },
    A88: { code: "J748.1", name: { zh: "線性軸承底座 (萬用試驗機)", en: "Base Linear Bearing" }, image: "jigs/A88.png", kind: { zh: "治具總成", en: "Fixture assembly" }, stock: 2, loc: "G02-01" },
    A89: { code: "J771.1", name: { zh: "負載缸轉接 M16", en: "Load Cylinder Adapter M16" }, image: "jigs/A89.png", kind: { zh: "轉接件", en: "Adaptor" }, stock: 2, loc: "R01-02" },
    A90: { code: "J777.1", name: { zh: "後穿軸假件 (NEW)", en: "Rear Thru Axle Dummy (NEW)" }, image: "jigs/A90.png", kind: { zh: "假件", en: "Dummy" }, stock: 1, loc: "D05-01" },
    A92: { code: "J587.2", name: { zh: "BB 固定 (萬用試驗機)", en: "BB Fixation (Universal TM)" }, image: "jigs/A92.png", kind: { zh: "固定座", en: "Fixation" }, stock: 2, loc: "X02-04" },
    A93: { code: "J648.1 / J647.1", name: { zh: "逆向落架墊片 (前+後) (NEW)", en: "Reverse Falling Frame Spacers (NEW)" }, image: "jigs/A93.png", kind: { zh: "墊片", en: "Spacer" }, stock: 1, loc: "S01-03" },
    A94: { code: "J584.1", name: { zh: "刷負載後輪轂 (含軸帽)", en: "Scrubload Rear Hub" }, image: "jigs/A94.png", kind: { zh: "輪轂", en: "Hub" }, stock: 2, loc: "H02-02" },
    A99: { code: "J753.1 / J751.1 / J749.1", name: { zh: "拉出測試工具 (M3/M4/M5)", en: "Pull-Out Tool (M3/M4/M5)" }, image: "jigs/A99.png", kind: { zh: "工具", en: "Tool" }, stock: 3, loc: "T02-01" },
    A100: { code: "J754.1 / J752.1 / J750.1", name: { zh: "最大鎖固扭力工具 (M3/M4/M5)", en: "Max. Bolt Torque Tool" }, image: "jigs/A100.png", kind: { zh: "工具", en: "Tool" }, stock: 3, loc: "T02-02" },
    A101: { code: "J782.1", name: { zh: "32吋 PED 側板後桿固定 (NEW)", en: "PED Side Plate Rear Rod Fix 32\"" }, image: "jigs/A101.png", kind: { zh: "固定座", en: "Fixation" }, stock: 2, loc: "X03-01" },
    A102: { code: "J790.1", name: { zh: "32吋 PED 桿延伸 (NEW)", en: "PED Rod Extension 32\" (NEW)" }, image: "jigs/A102.png", kind: { zh: "延伸件", en: "Extension" }, stock: 1, loc: "E01-02" },
    A106: { code: "J835.1", name: { zh: "IPU 轉向管假件", en: "IPU Steer Tube Dummy" }, image: "jigs/A106.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D05-02" },
    A107: { code: "J834.1", name: { zh: "IPU 夾環假件", en: "IPU Clamp Ring Dummy" }, image: "jigs/A107.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D05-03" },
    A108: { code: "J830.1", name: { zh: "IPU 龍頭假件", en: "IPU Stem Dummy" }, image: "jigs/A108.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D05-04" },
    A109: { code: "J772.1", name: { zh: "頂蓋假件", en: "Top Cap Dummy" }, image: "jigs/A109.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D06-01" },
    A110: { code: "J851.1", name: { zh: "IPU 把手假件", en: "IPU Handlebar Dummy" }, image: "jigs/A110.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D06-02" },
    A111: { code: "J833.1 / J832.1 / J831.1", name: { zh: "IPU 配重 (500/900/1250 g)", en: "IPU Weights" }, image: "jigs/A111.png", kind: { zh: "配重", en: "Weight" }, stock: 2, loc: "W01-01" },
    A112: { code: "J589.1", name: { zh: "後輪轂 Bottom Out", en: "Rear Hub Bottom Out" }, image: "jigs/A112.png", kind: { zh: "輪轂", en: "Hub" }, stock: 2, loc: "H02-03" },
    A113: { code: "J631.1 +J634.1", name: { zh: "座管假件 (萬用試驗機)", en: "Seatpost Dummy (Universal TM)" }, image: "jigs/A113.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D06-03" },
    A114: { code: "J836.1", name: { zh: "IPU 過載假件", en: "IPU Overload Dummy" }, image: "jigs/A114.png", kind: { zh: "假件", en: "Dummy" }, stock: 2, loc: "D06-04" },
  };
  window.DATA = window.DATA || {};
  window.DATA.PARTS = P;
})();
